package com.yozzibeens.rivostaxipartner.modelosApp;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table CABBIE.
 */
public class Coordenadas {

    public Coordenadas(String latitude, String longitude) {
        Latitude = latitude;
        Longitude = longitude;
    }

    public Coordenadas() {
    }

    public String getLongitude() {
        return Longitude;
    }

    public void setLongitude(String longitude) {
        Longitude = longitude;
    }

    public String getLatitude() {
        return Latitude;
    }

    public void setLatitude(String latitude) {
        Latitude = latitude;
    }


    private String Latitude;
    private String Longitude;




}
