package com.yozzibeens.rivostaxipartner.modelosApp;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table CABBIE.
 */
public class DatosSolicitud {

    public String getName() {
        return Name;
    }

    public void setName(String name) {
        Name = name;
    }

    public String getRequest_Id() {
        return Request_Id;
    }

    public void setRequest_Id(String request_Id) {
        Request_Id = request_Id;
    }

    public String getDate() {
        return Date;
    }

    public void setDate(String date) {
        Date = date;
    }

    public String getLatitude_In() {
        return Latitude_In;
    }

    public void setLatitude_In(String latitude_In) {
        Latitude_In = latitude_In;
    }

    public String getLongitude_In() {
        return Longitude_In;
    }

    public void setLongitude_In(String longitude_In) {
        Longitude_In = longitude_In;
    }

    public String getLatitude_Fn() {
        return Latitude_Fn;
    }

    public void setLatitude_Fn(String latitude_Fn) {
        Latitude_Fn = latitude_Fn;
    }

    public String getLongitude_Fn() {
        return Longitude_Fn;
    }

    public void setLongitude_Fn(String longitude_Fn) {
        Longitude_Fn = longitude_Fn;
    }

    public String getCabbie_Id() {
        return Cabbie_Id;
    }

    public void setCabbie_Id(String cabbie_Id) {
        Cabbie_Id = cabbie_Id;
    }

    public String getClient_Id() {
        return Client_Id;
    }

    public void setClient_Id(String client_Id) {
        Client_Id = client_Id;
    }

    public String getInicio() {
        return Inicio;
    }

    public void setInicio(String inicio) {
        Inicio = inicio;
    }

    public String getDestino() {
        return Destino;
    }

    public void setDestino(String destino) {
        Destino = destino;
    }

    private String Name;
    private String Request_Id;
    private String Date;
    private String Latitude_In;
    private String Longitude_In;
    private String Latitude_Fn;
    private String Longitude_Fn;
    private String Cabbie_Id;
    private String Client_Id;
    private String Inicio;
    private String Destino;

    public DatosSolicitud(String name, String request_Id, String date, String latitude_In, String longitude_In, String latitude_Fn, String longitude_Fn, String cabbie_Id, String client_Id, String inicio, String destino) {
        Name = name;
        Request_Id = request_Id;
        Date = date;
        Latitude_In = latitude_In;
        Longitude_In = longitude_In;
        Latitude_Fn = latitude_Fn;
        Longitude_Fn = longitude_Fn;
        Cabbie_Id = cabbie_Id;
        Client_Id = client_Id;
        Inicio = inicio;
        Destino = destino;
    }

    public DatosSolicitud(){
    }










}
