package com.yozzibeens.rivostaxipartner.modelosApp;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table CABBIE.
 */
public class Referencia {


    public Referencia(String client_Id, String cabbie_Id, String status) {
        Client_Id = client_Id;
        Cabbie_Id = cabbie_Id;
        Status = status;
    }
    public Referencia() {
    }

    public String getClient_Id() {
        return Client_Id;
    }

    public void setClient_Id(String client_Id) {
        Client_Id = client_Id;
    }

    public String getCabbie_Id() {
        return Cabbie_Id;
    }

    public void setCabbie_Id(String cabbie_Id) {
        Cabbie_Id = cabbie_Id;
    }

    public String getStatus() {
        return Status;
    }

    public void setStatus(String status) {
        Status = status;
    }

    private String Client_Id;
    private String Cabbie_Id;
    private String Status;




}
