package com.yozzibeens.rivostaxipartner.modelo;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.yozzibeens.rivostaxipartner.modelo.Cabbie;

import com.yozzibeens.rivostaxipartner.modelo.CabbieDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig cabbieDaoConfig;

    private final CabbieDao cabbieDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        cabbieDaoConfig = daoConfigMap.get(CabbieDao.class).clone();
        cabbieDaoConfig.initIdentityScope(type);

        cabbieDao = new CabbieDao(cabbieDaoConfig, this);

        registerDao(Cabbie.class, cabbieDao);
    }
    
    public void clear() {
        cabbieDaoConfig.getIdentityScope().clear();
    }

    public CabbieDao getCabbieDao() {
        return cabbieDao;
    }

}
